use binrw::{BinRead,BinWrite};
use modular_bitfield::prelude::*;

#[derive(BinRead, BinWrite,Debug,Copy, Clone)]
#[brw(repr(u32))]
pub enum ImageFormat
{
	IMAGE_FORMAT_UNKNOWN = -1,
	IMAGE_FORMAT_RGBA8888 = 0,
	IMAGE_FORMAT_ABGR8888,
	IMAGE_FORMAT_RGB888,
	IMAGE_FORMAT_BGR888,
	IMAGE_FORMAT_RGB565,
	IMAGE_FORMAT_I8,
	IMAGE_FORMAT_IA88,
	IMAGE_FORMAT_P8,
	IMAGE_FORMAT_A8,
	IMAGE_FORMAT_RGB888_BLUESCREEN,
	IMAGE_FORMAT_BGR888_BLUESCREEN,
	IMAGE_FORMAT_ARGB8888,
	IMAGE_FORMAT_BGRA8888,
	IMAGE_FORMAT_DXT1,
	IMAGE_FORMAT_DXT3,
	IMAGE_FORMAT_DXT5,
	IMAGE_FORMAT_BGRX8888,
	IMAGE_FORMAT_BGR565,
	IMAGE_FORMAT_BGRX5551,
	IMAGE_FORMAT_BGRA4444,
	IMAGE_FORMAT_DXT1_ONEBITALPHA,
	IMAGE_FORMAT_BGRA5551,
	IMAGE_FORMAT_UV88,
	IMAGE_FORMAT_UVWQ8888,
	IMAGE_FORMAT_RGBA16161616F,
	// GR - HDR
	IMAGE_FORMAT_RGBA16161616,
	IMAGE_FORMAT_UVLX8888,
	IMAGE_FORMAT_R32F,	// Single-channel 32-bit floating point
	IMAGE_FORMAT_RGB323232F,
	IMAGE_FORMAT_RGBA32323232F,
	IMAGE_FORMAT_LINEAR_BGRX8888,
	IMAGE_FORMAT_LINEAR_RGBA8888,
	IMAGE_FORMAT_LINEAR_ABGR8888,
	IMAGE_FORMAT_LINEAR_ARGB8888,
	IMAGE_FORMAT_LINEAR_BGRA8888,
	IMAGE_FORMAT_LINEAR_RGB888,
	IMAGE_FORMAT_LINEAR_BGR888,
	IMAGE_FORMAT_LINEAR_BGRX5551,
	IMAGE_FORMAT_LINEAR_I8,
	NUM_IMAGE_FORMATS
}

#[bitfield]
#[derive(BinRead,BinWrite,Debug,PartialEq)]
#[br(map = Self::from_bytes)]
pub struct ImageFlags{
TEXTUREFLAGS_POINTSAMPLE: bool,
TEXTUREFLAGS_TRILINEAR: bool,
TEXTUREFLAGS_CLAMPS: bool,
TEXTUREFLAGS_CLAMPT: bool,
TEXTUREFLAGS_ANISOTROPIC: bool,
TEXTUREFLAGS_HINT_DXT5: bool,
TEXTUREFLAGS_NOCOMPRESS: bool,
TEXTUREFLAGS_NORMAL: bool,
TEXTUREFLAGS_NOMIP: bool,
TEXTUREFLAGS_NOLOD: bool,
TEXTUREFLAGS_MINMIP: bool,
TEXTUREFLAGS_PROCEDURAL: bool,
TEXTUREFLAGS_ONEBITALPHA: bool,
TEXTUREFLAGS_EIGHTBITALPHA: bool,
TEXTUREFLAGS_ENVMAP: bool,
TEXTUREFLAGS_RENDERTARGET: bool,
TEXTUREFLAGS_DEPTHRENDERTARGET: bool,
TEXTUREFLAGS_NODEBUGOVERRIDE: bool,
TEXTUREFLAGS_SINGLECOPY: bool,
TEXTUREFLAGS_ONEOVERMIPLEVELINALPHA: bool,
TEXTUREFLAGS_PREMULTCOLORBYONEOVERMIPLEVEL: bool,
TEXTUREFLAGS_NORMALTODUDV: bool,
TEXTUREFLAGS_ALPHATESTMIPGENERATION: bool,
TEXTUREFLAGS_NODEPTHBUFFER: bool,
TEXTUREFLAGS_NICEFILTERED: bool,
TEXTUREFLAGS_CLAMPU: bool,
TEXTUREFLAGS_PRESWIZZLED: bool,
TEXTUREFLAGS_CACHEABLE: bool,
TEXTUREFLAGS_UNFILTERABLE_OK: bool,
TEXTUREFLAGS_UNK0x20000000: bool,
TEXTUREFLAGS_UNK0x40000000: bool,
TEXTUREFLAGS_UNK0x80000000: bool,
}

pub static ImageFormatBlock: &'static [usize] = &[4,4,3,3,2,1,2,1,1,3,3,4,4,8,16,16,4,2,2,2,8,2,2,4,8,8,4,4,12,16,4,4,4,4,4,3,3,2,1];